"""add campo ativo em Processo

Revision ID: b72510b1df7b
Revises: 
Create Date: 2025-08-25 10:05:54.329738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72510b1df7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
